"""baseline_tables

Revision ID: 158e804d7d39
Revises: 
Create Date: 2020-05-16 16:31:02.537595

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '158e804d7d39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('channel', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('expenses',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('payments', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('date')
    )
    op.create_table('products',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('sku', sa.String(length=50), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('price', sa.Float(precision=2), nullable=True),
    sa.PrimaryKeyConstraint('uid')
    )
    op.create_table('orders',
    sa.Column('uid', sa.Integer(), nullable=False),
    sa.Column('submitted_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Float(precision=2), nullable=True),
    sa.Column('shopify', sa.Boolean(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.uid'], ),
    sa.PrimaryKeyConstraint('uid', 'shopify')
    )
    op.create_table('orderitems',
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('shopify', sa.Boolean(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['order_id', 'shopify'], ['orders.uid', 'orders.shopify'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.uid'], ),
    sa.PrimaryKeyConstraint('order_id', 'shopify', 'product_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('orderitems')
    op.drop_table('orders')
    op.drop_table('products')
    op.drop_table('expenses')
    op.drop_table('companies')
    # ### end Alembic commands ###
